/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PriereRouteImport } from './routes/priere'
import { Route as PredicationsRouteImport } from './routes/predications'
import { Route as PasteurRouteImport } from './routes/pasteur'
import { Route as MinisteresRouteImport } from './routes/ministeres'
import { Route as GalerieRouteImport } from './routes/galerie'
import { Route as EvenementsRouteImport } from './routes/evenements'
import { Route as DonRouteImport } from './routes/don'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PriereRoute = PriereRouteImport.update({
  id: '/priere',
  path: '/priere',
  getParentRoute: () => rootRouteImport,
} as any)
const PredicationsRoute = PredicationsRouteImport.update({
  id: '/predications',
  path: '/predications',
  getParentRoute: () => rootRouteImport,
} as any)
const PasteurRoute = PasteurRouteImport.update({
  id: '/pasteur',
  path: '/pasteur',
  getParentRoute: () => rootRouteImport,
} as any)
const MinisteresRoute = MinisteresRouteImport.update({
  id: '/ministeres',
  path: '/ministeres',
  getParentRoute: () => rootRouteImport,
} as any)
const GalerieRoute = GalerieRouteImport.update({
  id: '/galerie',
  path: '/galerie',
  getParentRoute: () => rootRouteImport,
} as any)
const EvenementsRoute = EvenementsRouteImport.update({
  id: '/evenements',
  path: '/evenements',
  getParentRoute: () => rootRouteImport,
} as any)
const DonRoute = DonRouteImport.update({
  id: '/don',
  path: '/don',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/don': typeof DonRoute
  '/evenements': typeof EvenementsRoute
  '/galerie': typeof GalerieRoute
  '/ministeres': typeof MinisteresRoute
  '/pasteur': typeof PasteurRoute
  '/predications': typeof PredicationsRoute
  '/priere': typeof PriereRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/don': typeof DonRoute
  '/evenements': typeof EvenementsRoute
  '/galerie': typeof GalerieRoute
  '/ministeres': typeof MinisteresRoute
  '/pasteur': typeof PasteurRoute
  '/predications': typeof PredicationsRoute
  '/priere': typeof PriereRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/blog': typeof BlogRoute
  '/contact': typeof ContactRoute
  '/don': typeof DonRoute
  '/evenements': typeof EvenementsRoute
  '/galerie': typeof GalerieRoute
  '/ministeres': typeof MinisteresRoute
  '/pasteur': typeof PasteurRoute
  '/predications': typeof PredicationsRoute
  '/priere': typeof PriereRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/blog'
    | '/contact'
    | '/don'
    | '/evenements'
    | '/galerie'
    | '/ministeres'
    | '/pasteur'
    | '/predications'
    | '/priere'
    | '/sitemap.xml'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/blog'
    | '/contact'
    | '/don'
    | '/evenements'
    | '/galerie'
    | '/ministeres'
    | '/pasteur'
    | '/predications'
    | '/priere'
    | '/sitemap.xml'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/blog'
    | '/contact'
    | '/don'
    | '/evenements'
    | '/galerie'
    | '/ministeres'
    | '/pasteur'
    | '/predications'
    | '/priere'
    | '/sitemap.xml'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  BlogRoute: typeof BlogRoute
  ContactRoute: typeof ContactRoute
  DonRoute: typeof DonRoute
  EvenementsRoute: typeof EvenementsRoute
  GalerieRoute: typeof GalerieRoute
  MinisteresRoute: typeof MinisteresRoute
  PasteurRoute: typeof PasteurRoute
  PredicationsRoute: typeof PredicationsRoute
  PriereRoute: typeof PriereRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/priere': {
      id: '/priere'
      path: '/priere'
      fullPath: '/priere'
      preLoaderRoute: typeof PriereRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predications': {
      id: '/predications'
      path: '/predications'
      fullPath: '/predications'
      preLoaderRoute: typeof PredicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pasteur': {
      id: '/pasteur'
      path: '/pasteur'
      fullPath: '/pasteur'
      preLoaderRoute: typeof PasteurRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ministeres': {
      id: '/ministeres'
      path: '/ministeres'
      fullPath: '/ministeres'
      preLoaderRoute: typeof MinisteresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galerie': {
      id: '/galerie'
      path: '/galerie'
      fullPath: '/galerie'
      preLoaderRoute: typeof GalerieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evenements': {
      id: '/evenements'
      path: '/evenements'
      fullPath: '/evenements'
      preLoaderRoute: typeof EvenementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/don': {
      id: '/don'
      path: '/don'
      fullPath: '/don'
      preLoaderRoute: typeof DonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  BlogRoute: BlogRoute,
  ContactRoute: ContactRoute,
  DonRoute: DonRoute,
  EvenementsRoute: EvenementsRoute,
  GalerieRoute: GalerieRoute,
  MinisteresRoute: MinisteresRoute,
  PasteurRoute: PasteurRoute,
  PredicationsRoute: PredicationsRoute,
  PriereRoute: PriereRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
